DROP TABLE IF EXISTS Clients;

CREATE TABLE CLIENTS (
    ID_CLIENT   INTEGER      NOT NULL,
    FIRST_NAME_CLIENT VARCHAR(128) NOT NULL,
    LAST_NAME_CLIENT VARCHAR(128) NOT NULL,
    EMAIL_CLIENT VARCHAR(128) NOT NULL,
    PRIMARY KEY (id_client)
);

DROP TABLE IF EXISTS RATING;
CREATE TABLE RATING (
    ID_RATING   UUID      NOT NULL,
    DATE_RATING DATETIME NOT NULL,
    ID_CLIENT   INTEGER      NOT NULL,
    NUMBER_STARS_RATING  INTEGER      NOT NULL,
    PRIMARY KEY (ID_RATING)
);

